"""Integration test for Gmail reply sending.

Run with:
    pytest -m integration tests/integration/test_gmail_send_integration.py

This test sends a real email to INTEGRATION_TEST_RECIPIENT (set this to your
own address). It self-skips when token.pickle, INTEGRATION_TEST_RECIPIENT, or
the Gmail send scope are unavailable.
"""

import os

import pytest

pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not (os.path.exists("token.pickle") and os.getenv("INTEGRATION_TEST_RECIPIENT")),
        reason="Requires token.pickle + INTEGRATION_TEST_RECIPIENT env var",
    ),
]


def test_send_reply_threads_under_a_real_message():
    """Pick the most recent email in the inbox, reply to it, verify Gmail returns an id."""
    from app.gmail.service import get_recent_emails, send_reply

    recent = get_recent_emails(max_results=1, unread_only=False)
    if not recent:
        pytest.skip("Inbox empty — nothing to reply to")
    target = recent[0]

    new_id = send_reply(
        thread_id=target["thread_id"],
        message_id=target["id"],
        body=(
            "[ai-email-copilot integration test]\n\n"
            "Automated test reply — please ignore. Generated by tests/integration/"
            "test_gmail_send_integration.py."
        ),
    )

    assert new_id, "Gmail did not return a message id for the sent reply"
